spring.application.name=API-GATEWAY

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Routing

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=exam-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://EXAM-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/exams/**

spring.cloud.gateway.server.webflux.routes[2].id=submission-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://SUBMISSION-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/attempts/**

spring.cloud.gateway.server.webflux.routes[3].id=result-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://RESULT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/results/**